# Use this file to construct an environment
# for developing appose from source.
#
# First, install mambaforge:
#
#   https://github.com/conda-forge/miniforge#mambaforge
#
# Then run:
#
#   mamba env create -f dev-environment.yml
#   conda activate appose-dev
#
# In addition to the dependencies needed for using appose, it
# includes tools for developer-related actions like running
# automated tests (pytest) and linting the code (black). If you
# want an environment without these tools, use environment.yml.
name: appose-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.10
  # Project dependencies
  - numpy
  # Developer tools
  - autopep8
  - black
  - build
  - flake8
  - isort
  - pytest
  - toml
  # Project from source
  - pip
  - pip:
    - validate-pyproject[all]
    - -e .
