# Use this file to construct an environment for
# working with appose in a runtime setting.
#
# First, install mambaforge:
#
#   https://github.com/conda-forge/miniforge#mambaforge
#
# Then run:
#
#   mamba env create
#   mamba activate appose
#
# It includes the dependencies needed for using appose, but not tools
# for developer-related actions like running automated tests (pytest),
# linting the code (black), and generating the API documentation (sphinx).
# If you want an environment including these tools, use dev-environment.yml.

name: appose
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.8
  # Project dependencies
  - jgo
  - numpy
  - openjdk >= 8
  # Project from source
  - pip
  - pip:
    - -e .
